plugins {
    id 'io.freefair.lombok' version '9.5.0'
    id 'java'
    id 'application'
    id 'checkstyle'
    id 'jacoco'
    id 'maven-publish'
}

group = 'me.motemere'
version = '1.0.0'

application {
    mainClass = 'me.motemere.code.app.App'
}

java {
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.13.3'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.13.3'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher:1.13.3'

    testImplementation 'com.google.truth:truth:1.4.4'
    testImplementation 'org.mockito:mockito-core:5.18.0'

    testImplementation 'org.assertj:assertj-core:3.27.7'

    compileOnly 'org.projectlombok:lombok:1.18.38'
    annotationProcessor 'org.projectlombok:lombok:1.18.38'

    testCompileOnly 'org.projectlombok:lombok:1.18.38'
    testAnnotationProcessor 'org.projectlombok:lombok:1.18.38'
}

jacocoTestReport {
    reports {
        xml.required = true
    }
}

test {
    useJUnitPlatform()
    finalizedBy jacocoTestReport
}

checkstyle {
    configFile = file('config/checkstyle/checkstyle.xml')
    toolVersion = '10.26.1'
}

publishing {
    publications {
        gpr(MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven {
            name = 'GitHubPackages'
            url = uri('https://maven.pkg.github.com/motemere/lafore-java')
            credentials {
                username = System.getenv('USERNAME')
                password = System.getenv('TOKEN')
            }
        }
    }
}
