plugins {
    id "io.freefair.lombok" version "8.4"
    id "java"
    id "application"
    id "checkstyle"
    id "jacoco"
}

group = "me.motemere"
version = "0.0.3"

application {
    mainClass = "me.motemere.code.app.App"
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.13.3'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.13.3'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher:1.13.3'

    testImplementation group: "com.google.truth", name: "truth", version: "1.4.4"
    testImplementation group: "org.mockito", name: "mockito-core", version: "5.18.0"

    testImplementation 'org.assertj:assertj-core:3.27.3'

    compileOnly 'org.projectlombok:lombok:1.18.38'
    annotationProcessor "org.projectlombok:lombok:1.18.38"

    testCompileOnly "org.projectlombok:lombok:1.18.38"
    testAnnotationProcessor "org.projectlombok:lombok:1.18.38"
}

tasks.named('test') {
    useJUnitPlatform()
}

checkstyle {
    configFile = file("config/checkstyle/checkstyle.xml")
    toolVersion "10.26.1"
}